//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberGuessingGame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumberGuessingGame.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP NET MVC (1DV409).
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓.
        /// </summary>
        public static string DownArrow {
            get {
                return ResourceManager.GetString("DownArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femte.
        /// </summary>
        public static string Fifth {
            get {
                return ResourceManager.GetString("Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Första.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjärde.
        /// </summary>
        public static string Forth {
            get {
                return ResourceManager.GetString("Forth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga fler gissningar!.
        /// </summary>
        public static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  gissningen.
        /// </summary>
        public static string Guess {
            get {
                return ResourceManager.GetString("Guess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gissa ett tal mellan 1 och 100:.
        /// </summary>
        public static string GuessName {
            get {
                return ResourceManager.GetString("GuessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talet måste vara mellan 1 och 100..
        /// </summary>
        public static string GuessRangeError {
            get {
                return ResourceManager.GetString("GuessRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste göra en gissning..
        /// </summary>
        public static string GuessRequiredError {
            get {
                return ResourceManager.GetString("GuessRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gissningen misslyckades. Rätta till felet och försök igen..
        /// </summary>
        public static string GuessSumError {
            get {
                return ResourceManager.GetString("GuessSumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gissa det hemliga talet.
        /// </summary>
        public static string GuessTitle {
            get {
                return ResourceManager.GetString("GuessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} är för högt..
        /// </summary>
        public static string HighGuessMessage {
            get {
                return ResourceManager.GetString("HighGuessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} är för lågt..
        /// </summary>
        public static string LowGuessMessage {
            get {
                return ResourceManager.GetString("LowGuessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slumpa nytt hemliga tal.
        /// </summary>
        public static string NewNumber {
            get {
                return ResourceManager.GetString("NewNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga fler gissningar! Det hemliga talet var {0}..
        /// </summary>
        public static string NoMoreGuessesMessage {
            get {
                return ResourceManager.GetString("NoMoreGuessesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har redan gissat på talet {0}!.
        /// </summary>
        public static string OldGuessMessage {
            get {
                return ResourceManager.GetString("OldGuessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laborationsuppgift 1.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Börja om.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rätt gissat!.
        /// </summary>
        public static string RightGuess {
            get {
                return ResourceManager.GetString("RightGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grattis du klarade det på {0} försöket..
        /// </summary>
        public static string RightGuessMessage {
            get {
                return ResourceManager.GetString("RightGuessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linnéuniversitetet.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andra.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelomgången kunde inte fullföljas.
        /// </summary>
        public static string SessionErrorTitle {
            get {
                return ResourceManager.GetString("SessionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sjunde.
        /// </summary>
        public static string Seventh {
            get {
                return ResourceManager.GetString("Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sjätte.
        /// </summary>
        public static string Sixth {
            get {
                return ResourceManager.GetString("Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steg 1.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tredje.
        /// </summary>
        public static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑.
        /// </summary>
        public static string UpArrow {
            get {
                return ResourceManager.GetString("UpArrow", resourceCulture);
            }
        }
    }
}
